# Objective Server Details
$OBJ_SERVER_NAME='REPLACEME_OBJ_SERVER_NAME_REPLACEME'
$OBJ_SERVER_PORT='REPLACEME_OBJ_SERVER_PORT_REPLACEME'
$OBJ_SERVER_USER='REPLACEME_OBJ_SERVER_USER_REPLACEME'
$OBJ_SERVER_PASS='REPLACEME_OBJ_SERVER_PASS_REPLACEME'

# Objective Datbaase Details
$OBJ_DB_SERVER='REPLACEME_OBJ_DB_SERVER_REPLACEME'
$OBJ_DB_NAME='REPLACEME_OBJ_DB_NAME_REPLACEME'
$OBJ_DB_USER='REPLACEME_OBJ_DB_USER_REPLACEME'
$OBJ_DB_PASS='REPLACEME_OBJ_DB_PASS_REPLACEME'

###### Note that the GIT Tool will user the Default Database for the user specified in $OBJ_DB_USER when looking for the log tables.
###### The OBJ_DB_NAME is specified so that the validation sql can check that the default database is the Objective database.

# Staging Datbaase Details
$STAGING_DB_SERVER='REPLACEME_STAGING_DB_SERVER_REPLACEME'
$STAGING_DB_NAME='REPLACEME_STAGING_DB_NAME_REPLACEME'
$STAGING_DB_USER='REPLACEME_STAGING_DB_USER_REPLACEME'
$STAGING_DB_PASS='REPLACEME_STAGING_DB_PASS_REPLACEME'


# RUNTIME Variables
$TIMESTAMP = get-date -Format 'yyyyMMdd_HHmmss'

# Path Details
$PROJECT_BASE_PATH='REPLACEME_PROJECT_BASE_PATH_REPLACEME'
$PROJECT_BIN_PATH="$PROJECT_BASE_PATH\bin"
$PROJECT_RUN_PATH="$PROJECT_BASE_PATH\run"
$PROJECT_EXTRACT_PATH="$PROJECT_BASE_PATH\extract"
$PROJECT_TRANSFORM_PATH="$PROJECT_BASE_PATH\transform"
$PROJECT_LOAD_PATH="$PROJECT_BASE_PATH\load"


